import { create } from "zustand";
import { persist } from "zustand/middleware";

const translations = {
  en: {
    // Nav
    home: "Home", virtualTour: "Virtual Tour", exploreMap: "Explore Map",
    archives: "Archives", calendar: "Calendar", travelGuide: "Travel Guide",
    contact: "Contact Us", login: "Login", signup: "Sign Up", dashboard: "Dashboard",
    logout: "Logout", admin: "Admin Panel", explore: "Explore", plan: "Plan",
    experience: "Experience",
    // Common
    search: "Search", close: "Close", share: "Share", loading: "Loading...",
    viewTour: "View 360°", language: "Language", namaste: "Namaste",
    send: "Send", submit: "Submit", cancel: "Cancel", save: "Save",
    delete: "Delete", edit: "Edit", back: "Back", next: "Next",
    // Virtual Tour
    heroTitle: "360° Virtual Tour",
    heroDesc: "Step inside Sikkim's ancient monasteries. Explore their history, architecture, and spiritual significance.",
    noResults: "No monasteries found.",
    dragToOrbit: "Drag to orbit · Click a marker to explore",
    history: "History", highlights: "Highlights", timings: "Timings",
    nearby: "Nearby", audioGuide: "Audio Guide",
    // Map
    interactiveMap: "Interactive Map", directions: "Directions",
    getDirections: "Get Directions", allRegions: "All Regions",
    followMe: "Follow Me", following: "Following",
    selectMonastery: "Click a monastery marker to see the route.",
    // Archives
    digitalArchives: "Digital Archives", manuscripts: "Manuscripts",
    murals: "Murals", photos: "Photos", documents: "Documents",
    wikimediaGallery: "Wikimedia Gallery", noArchives: "No archives found.",
    // Calendar
    festivalCalendar: "Festival Calendar", today: "Today",
    previous: "Previous", allFestivals: "All Festivals This Year",
    // Contact
    getInTouch: "Get in Touch", name: "Name", email: "Email",
    subject: "Subject", message: "Message", sendMessage: "Send Message",
    sending: "Sending...", office: "Office", phone: "Phone",
    quickFaq: "Quick FAQ",
    contactDesc: "Questions, feedback, or collaboration ideas? We're here to help.",
    // Auth
    welcomeBack: "Welcome Back", createAccount: "Create Your Account",
    fullName: "Full Name", password: "Password", loggingIn: "Logging in...",
    creatingAccount: "Creating Account...", noAccount: "Don't have an account?",
    haveAccount: "Already have an account?", role: "Role",
    user: "User", adminRole: "Admin",
    loginDesc: "Continue your journey through Sikkim's sacred heritage.",
    signupDesc: "Start exploring Sikkim's sacred heritage",
    // Dashboard
    upcomingTrips: "Upcoming Trips", recentActivity: "Recent Activity",
    quickActions: "Quick Actions", yourWishlist: "Your Wishlist",
    startExploring: "Start Exploring", planNewTrip: "+ Plan New Trip",
    tripsCompleted: "Trips", placesVisited: "Places Visited",
    daysExplored: "Days Explored", monasteriesAvailable: "Monasteries Available",
    weather: "Weather", level: "Level", xpToNext: "XP to next level",
    // Travel Guide
    sikkimTravelGuide: "Sikkim Travel Guide",
    travelGuideDesc: "Everything you need to know before visiting Sikkim's sacred monasteries.",
    bestTime: "Best Time to Visit", permits: "Permits & Entry",
    etiquette: "Monastery Etiquette", packing: "Packing Essentials",
    readyToExplore: "Ready to explore?", viewMap: "View Map",
    // Footer
    footerDesc: "Digitizing Sikkim's monastic heritage through immersive virtual tours, interactive maps, and AI-powered cultural guides.",
    resources: "Resources", connect: "Connect", allRights: "All rights reserved.",
    builtFor: "Built for Smart India Hackathon 2025",
    // Chatbot
    chatbotGreeting: "Namaste! 🙏 I'm the MysticSikkim AI guide. Ask me about monasteries, festivals, travel tips, or anything about Sikkim.",
    askAboutSikkim: "Ask about Sikkim...",
    alwaysHere: "Always here to help",
  },
  hi: {
    home: "होम", virtualTour: "वर्चुअल टूर", exploreMap: "मैप देखें",
    archives: "अभिलेख", calendar: "कैलेंडर", travelGuide: "यात्रा गाइड",
    contact: "संपर्क करें", login: "लॉगिन", signup: "साइन अप", dashboard: "डैशबोर्ड",
    logout: "लॉगआउट", admin: "एडमिन पैनल", explore: "अन्वेषण", plan: "योजना",
    experience: "अनुभव",
    search: "खोजें", close: "बंद करें", share: "शेयर करें", loading: "लोड हो रहा...",
    viewTour: "360° देखें", language: "भाषा", namaste: "नमस्ते",
    send: "भेजें", submit: "जमा करें", cancel: "रद्द करें", save: "सहेजें",
    delete: "हटाएं", edit: "संपादित करें", back: "वापस", next: "आगे",
    heroTitle: "360° वर्चुअल टूर",
    heroDesc: "सिक्किम के प्राचीन मठों में प्रवेश करें। उनके इतिहास, वास्तुकला और आध्यात्मिक महत्व का अन्वेषण करें।",
    noResults: "कोई मठ नहीं मिला।",
    dragToOrbit: "घुमाने के लिए खींचें · मार्कर पर क्लिक करें",
    history: "इतिहास", highlights: "मुख्य बातें", timings: "समय",
    nearby: "आस-पास", audioGuide: "ऑडियो गाइड",
    interactiveMap: "इंटरएक्टिव मैप", directions: "दिशाएं",
    getDirections: "दिशा प्राप्त करें", allRegions: "सभी क्षेत्र",
    followMe: "मुझे फॉलो करें", following: "फॉलो कर रहे",
    selectMonastery: "मार्ग देखने के लिए मठ मार्कर पर क्लिक करें।",
    digitalArchives: "डिजिटल अभिलेख", manuscripts: "पांडुलिपियाँ",
    murals: "भित्ति चित्र", photos: "फोटो", documents: "दस्तावेज़",
    wikimediaGallery: "विकिमीडिया गैलरी", noArchives: "कोई अभिलेख नहीं मिला।",
    festivalCalendar: "उत्सव कैलेंडर", today: "आज",
    previous: "पिछला", allFestivals: "इस वर्ष के सभी उत्सव",
    getInTouch: "संपर्क करें", name: "नाम", email: "ईमेल",
    subject: "विषय", message: "संदेश", sendMessage: "संदेश भेजें",
    sending: "भेज रहे हैं...", office: "कार्यालय", phone: "फोन",
    quickFaq: "सामान्य प्रश्न",
    contactDesc: "प्रश्न, प्रतिक्रिया, या सहयोग विचार? हम सहायता के लिए यहाँ हैं।",
    welcomeBack: "वापस स्वागत है", createAccount: "अपना खाता बनाएं",
    fullName: "पूरा नाम", password: "पासवर्ड", loggingIn: "लॉगिन हो रहा...",
    creatingAccount: "खाता बन रहा...", noAccount: "खाता नहीं है?",
    haveAccount: "पहले से खाता है?", role: "भूमिका",
    user: "उपयोगकर्ता", adminRole: "एडमिन",
    loginDesc: "सिक्किम की पवित्र विरासत की यात्रा जारी रखें।",
    signupDesc: "सिक्किम की पवित्र विरासत का अन्वेषण शुरू करें",
    upcomingTrips: "आगामी यात्राएं", recentActivity: "हाल की गतिविधि",
    quickActions: "त्वरित कार्य", yourWishlist: "आपकी विशलिस्ट",
    startExploring: "अन्वेषण शुरू करें", planNewTrip: "+ नई यात्रा योजना",
    tripsCompleted: "यात्राएं", placesVisited: "देखे गए स्थान",
    daysExplored: "अन्वेषण दिवस", monasteriesAvailable: "उपलब्ध मठ",
    weather: "मौसम", level: "स्तर", xpToNext: "अगले स्तर के लिए XP",
    sikkimTravelGuide: "सिक्किम यात्रा गाइड",
    travelGuideDesc: "सिक्किम के पवित्र मठों की यात्रा से पहले जानने योग्य सब कुछ।",
    bestTime: "सबसे अच्छा समय", permits: "परमिट और प्रवेश",
    etiquette: "मठ शिष्टाचार", packing: "पैकिंग आवश्यकताएं",
    readyToExplore: "अन्वेषण के लिए तैयार?", viewMap: "मैप देखें",
    footerDesc: "सिक्किम की मठ विरासत का डिजिटलीकरण।",
    resources: "संसाधन", connect: "जुड़ें", allRights: "सर्वाधिकार सुरक्षित।",
    builtFor: "स्मार्ट इंडिया हैकाथॉन 2025 के लिए बनाया गया",
    chatbotGreeting: "नमस्ते! 🙏 मैं MysticSikkim AI गाइड हूँ। मठों, त्योहारों, यात्रा सुझावों के बारे में पूछें।",
    askAboutSikkim: "सिक्किम के बारे में पूछें...",
    alwaysHere: "हमेशा मदद के लिए यहाँ",
  },
  ne: {
    home: "गृहपृष्ठ", virtualTour: "भर्चुअल टूर", exploreMap: "नक्सा हेर्नुहोस्",
    archives: "अभिलेखालय", calendar: "पात्रो", travelGuide: "यात्रा गाइड",
    contact: "सम्पर्क", login: "लगइन", signup: "साइन अप", dashboard: "ड्यासबोर्ड",
    logout: "लगआउट", admin: "एडमिन प्यानल", explore: "अन्वेषण", plan: "योजना",
    experience: "अनुभव",
    search: "खोज्नुहोस्", close: "बन्द", share: "साझा गर्नुहोस्", loading: "लोड हुँदैछ...",
    viewTour: "360° हेर्नुहोस्", language: "भाषा", namaste: "नमस्ते",
    send: "पठाउनुहोस्", submit: "पेश गर्नुहोस्", cancel: "रद्द", save: "सुरक्षित गर्नुहोस्",
    delete: "मेट्नुहोस्", edit: "सम्पादन", back: "पछाडि", next: "अर्को",
    heroTitle: "360° भर्चुअल टूर",
    heroDesc: "सिक्किमका प्राचीन मठहरूमा प्रवेश गर्नुहोस्। तिनीहरूको इतिहास, वास्तुकला र आध्यात्मिक महत्व अन्वेषण गर्नुहोस्।",
    noResults: "कुनै मठ भेटिएन।",
    dragToOrbit: "घुमाउन तान्नुहोस् · मार्कर क्लिक गर्नुहोस्",
    history: "इतिहास", highlights: "मुख्य विशेषता", timings: "समय",
    nearby: "नजिकै", audioGuide: "अडियो गाइड",
    interactiveMap: "अन्तरक्रियात्मक नक्सा", directions: "दिशाहरू",
    getDirections: "दिशा प्राप्त गर्नुहोस्", allRegions: "सबै क्षेत्र",
    followMe: "मलाई फलो गर्नुहोस्", following: "फलो गर्दै",
    selectMonastery: "मार्ग हेर्न मठ मार्कर क्लिक गर्नुहोस्।",
    digitalArchives: "डिजिटल अभिलेखालय", manuscripts: "पाण्डुलिपि",
    murals: "भित्तिचित्र", photos: "फोटो", documents: "कागजात",
    wikimediaGallery: "विकिमिडिया ग्यालरी", noArchives: "कुनै अभिलेख भेटिएन।",
    festivalCalendar: "चाड पर्व पात्रो", today: "आज",
    previous: "अघिल्लो", allFestivals: "यस वर्षका सबै चाडपर्व",
    getInTouch: "सम्पर्कमा रहनुहोस्", name: "नाम", email: "इमेल",
    subject: "विषय", message: "सन्देश", sendMessage: "सन्देश पठाउनुहोस्",
    sending: "पठाउँदैछ...", office: "कार्यालय", phone: "फोन",
    quickFaq: "सामान्य प्रश्न",
    contactDesc: "प्रश्न, प्रतिक्रिया वा सहकार्य विचार? हामी सहयोगका लागि यहाँ छौं।",
    welcomeBack: "फेरि स्वागत छ", createAccount: "आफ्नो खाता बनाउनुहोस्",
    fullName: "पूरा नाम", password: "पासवर्ड", loggingIn: "लगइन हुँदैछ...",
    creatingAccount: "खाता बनाउँदैछ...", noAccount: "खाता छैन?",
    haveAccount: "पहिले नै खाता छ?", role: "भूमिका",
    user: "प्रयोगकर्ता", adminRole: "एडमिन",
    loginDesc: "सिक्किमको पवित्र सम्पदाको यात्रा जारी राख्नुहोस्।",
    signupDesc: "सिक्किमको पवित्र सम्पदा अन्वेषण सुरु गर्नुहोस्",
    upcomingTrips: "आगामी यात्राहरू", recentActivity: "हालको गतिविधि",
    quickActions: "द्रुत कार्यहरू", yourWishlist: "तपाईंको विशलिस्ट",
    startExploring: "अन्वेषण सुरु गर्नुहोस्", planNewTrip: "+ नयाँ यात्रा योजना",
    tripsCompleted: "यात्राहरू", placesVisited: "भ्रमण गरिएका ठाउँ",
    daysExplored: "अन्वेषण दिन", monasteriesAvailable: "उपलब्ध मठ",
    weather: "मौसम", level: "स्तर", xpToNext: "अर्को स्तरको लागि XP",
    sikkimTravelGuide: "सिक्किम यात्रा गाइड",
    travelGuideDesc: "सिक्किमका पवित्र मठहरू भ्रमण गर्नुअघि जान्नुपर्ने सबै कुरा।",
    bestTime: "उत्तम समय", permits: "अनुमति र प्रवेश",
    etiquette: "मठ शिष्टाचार", packing: "प्याकिङ आवश्यकता",
    readyToExplore: "अन्वेषणको लागि तयार?", viewMap: "नक्सा हेर्नुहोस्",
    footerDesc: "सिक्किमको मठ सम्पदाको डिजिटलीकरण।",
    resources: "स्रोतहरू", connect: "जोडिनुहोस्", allRights: "सर्वाधिकार सुरक्षित।",
    builtFor: "स्मार्ट इन्डिया ह्याकाथन 2025 का लागि निर्मित",
    chatbotGreeting: "नमस्ते! 🙏 म MysticSikkim AI गाइड हुँ। मठ, चाडपर्व, यात्रा सुझावको बारेमा सोध्नुहोस्।",
    askAboutSikkim: "सिक्किमको बारेमा सोध्नुहोस्...",
    alwaysHere: "सधैं सहयोगका लागि यहाँ",
  },
  bo: {
    home: "གཙོ་ངོས།", virtualTour: "དངོས་མེད་འཁོར་ལམ།", exploreMap: "ས་ཁྲ།",
    archives: "ཡིག་ཚགས།", calendar: "ལོ་ཐོ།", travelGuide: "འགྲུལ་བཞུད་ལམ་སྟོན།",
    contact: "འབྲེལ་གཏུགས།", login: "ནང་འཛུལ།", signup: "ཐོ་འགོད།", dashboard: "ལས་སྟེགས།",
    logout: "ཕྱིར་འཐོན།", admin: "དོ་དམ་སྡེ།", explore: "རྟོག་ཞིབ།", plan: "འཆར་གཞི།",
    experience: "ཉམས་མྱོང།",
    search: "འཚོལ།", close: "སྒོ་རྒྱག", share: "མཉམ་སྤྱོད།", loading: "སྣོན་འཇུག...",
    viewTour: "360° བལྟ།", language: "སྐད་ཡིག", namaste: "བཀྲ་ཤིས་བདེ་ལེགས།",
    send: "གཏོང།", submit: "འབུལ།", cancel: "ཕྱིར་འཐེན།", save: "ཉར།",
    delete: "སུབ།", edit: "བཅོས།", back: "ཕྱིར།", next: "རྗེས་མ།",
    heroTitle: "360° དངོས་མེད་འཁོར་ལམ།",
    heroDesc: "སིཀྐིམ་གྱི་དགོན་པ་རྙིང་པ་རྣམས་ལ་འཛུལ། ལོ་རྒྱུས་དང་བཟོ་རིག་གཟིགས།",
    noResults: "དགོན་པ་མ་རྙེད།",
    dragToOrbit: "འཁོར་བར་འཐེན། · རྟགས་ལ་མནན།",
    history: "ལོ་རྒྱུས།", highlights: "གཙོ་གནད།", timings: "དུས་ཚོད།",
    nearby: "ཉེ་འགྲམ།", audioGuide: "སྒྲ་ལམ་སྟོན།",
    interactiveMap: "ས་ཁྲ།", directions: "ལམ་སྟོན།",
    getDirections: "ལམ་སྟོན་ལེན།", allRegions: "ས་ཁུལ་ཡོངས།",
    followMe: "ང་ལ་རྗེས་འབྲངས།", following: "རྗེས་འབྲངས་བྱེད་བཞིན།",
    selectMonastery: "ལམ་བརྡ་མཐོང་བར་དགོན་པའི་རྟགས་མནན།",
    digitalArchives: "ཡིག་ཚགས་གསོག", manuscripts: "དཔེ་ཆ།",
    murals: "ལྡེབས་རིས།", photos: "པར།", documents: "ཡིག་ཆ།",
    wikimediaGallery: "པར་མཛོད།", noArchives: "ཡིག་ཚགས་མ་རྙེད།",
    festivalCalendar: "དུས་ཆེན་ལོ་ཐོ།", today: "དེ་རིང།",
    previous: "སྔོན་མ།", allFestivals: "ལོ་འདིའི་དུས་ཆེན་ཡོངས།",
    getInTouch: "འབྲེལ་གཏུགས།", name: "མིང།", email: "གློག་འཕྲིན།",
    subject: "བརྗོད་གཞི།", message: "འཕྲིན་ཐུང།", sendMessage: "འཕྲིན་གཏོང།",
    sending: "གཏོང་བཞིན...", office: "ལས་ཁུངས།", phone: "ཁ་པར།",
    quickFaq: "དྲི་བ།",
    contactDesc: "དྲི་བ་དང་བསམ་ཚུལ་ཡོད་ན་འབྲེལ་གཏུགས་གནང།",
    welcomeBack: "བསུ་བ་ཞུ།", createAccount: "ཐོ་འགོད་གསར་བཟོ།",
    fullName: "མིང་ཚང་མ།", password: "གསང་ཨང།", loggingIn: "ནང་འཛུལ་བྱེད་བཞིན...",
    creatingAccount: "ཐོ་འགོད་བྱེད་བཞིན...", noAccount: "ཐོ་འགོད་མེད་དམ?",
    haveAccount: "ཐོ་འགོད་ཡོད་དམ?", role: "འགན།",
    user: "སྤྱོད་མཁན།", adminRole: "དོ་དམ་པ།",
    loginDesc: "སིཀྐིམ་གྱི་རིག་གཞུང་འགྲུལ་བཞུད་མུ་མཐུད།",
    signupDesc: "སིཀྐིམ་གྱི་རིག་གཞུང་རྟོག་ཞིབ་འགོ་བརྩམས།",
    upcomingTrips: "འགྲུལ་བཞུད་འཆར་གཞི།", recentActivity: "ཉེ་ཆར་གྱི་བྱ་བ།",
    quickActions: "མགྱོགས་པའི་བྱ་བ།", yourWishlist: "ཁྱེད་ཀྱི་འདོད་ཐོ།",
    startExploring: "རྟོག་ཞིབ་འགོ་བརྩམས།", planNewTrip: "+ འགྲུལ་བཞུད་གསར་པ།",
    tripsCompleted: "འགྲུལ་བཞུད།", placesVisited: "ས་གནས་བལྟས་ཟིན།",
    daysExplored: "ཉིན་གྲངས།", monasteriesAvailable: "དགོན་པ།",
    weather: "གནམ་གཤིས།", level: "རིམ་པ།", xpToNext: "རིམ་པ་རྗེས་མར།",
    sikkimTravelGuide: "སིཀྐིམ་འགྲུལ་བཞུད་ལམ་སྟོན།",
    travelGuideDesc: "སིཀྐིམ་གྱི་དགོན་པ་བལྟ་བར་མ་འགྲོ་གོང་ཤེས་དགོས་པ།",
    bestTime: "དུས་ཚོད་བཟང་ཤོས།", permits: "ཆོག་མཆན།",
    etiquette: "དགོན་པའི་སྤྱོད་ལམ།", packing: "ཐུམ་བུ།",
    readyToExplore: "རྟོག་ཞིབ་ལ་གྲ་སྒྲིག?", viewMap: "ས་ཁྲ་བལྟ།",
    footerDesc: "སིཀྐིམ་གྱི་དགོན་པ་རིག་གཞུང་གི་ཨང་བསྒྱུར།",
    resources: "ཐོན་ཁུངས།", connect: "འབྲེལ་མཐུད།", allRights: "ཐོབ་ཐང་བཅུད།",
    builtFor: "SIH 2025 དོན་དུ་བཟོས།",
    chatbotGreeting: "བཀྲ་ཤིས་བདེ་ལེགས! 🙏 ང་MysticSikkim AI ལམ་སྟོན་པ་ཡིན། དགོན་པ་དང་དུས་ཆེན་སྐོར་དྲིས།",
    askAboutSikkim: "སིཀྐིམ་སྐོར་དྲིས...",
    alwaysHere: "རྒྱུན་དུ་གྲོགས་རམ་ལ་ཡོད།",
  },
};

const LANGUAGES = [
  { code: "en", name: "English", native: "English" },
  { code: "hi", name: "Hindi", native: "हिन्दी" },
  { code: "ne", name: "Nepali", native: "नेपाली" },
  { code: "bo", name: "Tibetan", native: "བོད་སྐད།" },
];

const useLanguageStore = create(
  persist(
    (set, get) => ({
      currentLang: "en",
      setLang: (lang) => set({ currentLang: lang }),
      t: (key) => {
        const lang = get().currentLang;
        return translations[lang]?.[key] || translations.en[key] || key;
      },
      languages: LANGUAGES,
    }),
    { name: "mystic-sikkim-lang" }
  )
);

export default useLanguageStore;
